первая версия
kit-cpp-course/kaneva-mp pull request #1
Opened 2018-12-24 07:45 UTC by kaneva-mp

2018-12-26 12:29 UTC, alpatov requested changes
Нужно исправить небольшие замечания.
Самое важное - управление памятью - правило трёх!!!

2018-12-26 12:29 UTC, alpatov commented on ClassTriangulation.hpp
> +class ClassTriangulation {
Префикс Class стоит убрать.

2018-12-26 12:29 UTC, alpatov commented on FileEditor.cpp
> +fileEditor::fileEditor(const std::string & path) {
Открытие файла лучше перенести в список инициализаторов.

2018-12-26 12:29 UTC, alpatov commented on FileEditor.hpp
> +    fileEditor(const std::string & path);
Если файл открывается в конструкторе, то в деструкторе стоит его закрывать.

2018-12-26 12:29 UTC, alpatov commented on List.hpp
> +    point * cur;
1. Динамическую память нужно инкапсулировать. 
2. Если у нас есть динамическая переменная, необходимо соблюдать правило трёх!!!

2018-12-26 12:29 UTC, alpatov commented on main.cpp
> +        ClassFile & file = editor;
Нет необходимости создавать переменную editor. Если мы хотим обобщить, то делать это стоит следующим образом:

ClassFile & file = fileEditor(path);
// ...

2018-12-26 12:29 UTC, alpatov commented on main.cpp
> +    }
Если параметры не корректны, то нужно вывести пользователю сообщение.

2018-12-26 12:29 UTC, alpatov commented on trianglation.hpp
> +    ~trianglation() {   delete [] list; delete [] first;
Перенести в cpp-файл.

2018-12-26 12:29 UTC, alpatov commented on trianglation.hpp
> +    List * list;
Правило трёх!!!

2018-12-26 12:29 UTC, alpatov commented on triangle.hpp
> +    static bool is_in_triangle (point * first, point * second, point * third, point * cur) {
Перенести в cpp-файл.

2018-12-26 12:29 UTC, alpatov commented on triangle.hpp
> +        for (int i = 0; i < points.size(); i++)
Скобки!!!

2018-12-27 20:25 UTC, kaneva-mp commented on FileEditor.cpp
> +fileEditor::fileEditor(const std::string & path) {
Не получилось. Не могли бы вы подсказать как это сделать?

2018-12-27 20:25 UTC, kaneva-mp commented on main.cpp
> +        ClassFile & file = editor;
Ругается и выдает ошибку, если пытаюсь так сделать

2018-12-27 20:27 UTC, kaneva-mp commented on List.hpp
> +    point * cur;
Для класса List сделан метод копирования, но для класса point 
не смогла сделать, так как есть поле "следующий", "предыдущий" и неизвестно, сколько там точек

2018-12-28 07:20 UTC, alpatov approved these changes

2018-12-28 07:20 UTC, alpatov commented on FileEditor.cpp
> +fileEditor::fileEditor(const std::string & path) {
`fileEditor::fileEditor(const std::string & path) : writeFile(path + name, ios::app) {}`

2019-01-21 18:25 UTC, closed without merging